version: "3"
services:
 pg_master:
  build: .
  volumes:
   - ./pg_data:/var/lib/postgresql/data
  ports:
    - 5499:5432
  environment:
   - POSTGRES_USER=hamed
   - POSTGRES_PASSWORD=123456
   - POSTGRES_DB=hamed
   - PG_REP_USER=rep
   - PG_REP_PASSWORD=123456
